# Generated by Django 5.0.3 on 2024-03-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_taskcommand'),
        ('user', '0002_alter_command_options_command_user_commanduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.command'),
        ),
        migrations.DeleteModel(
            name='TaskCommand',
        ),
    ]
