# Generated by Django 5.0.3 on 2024-04-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AddField(
            model_name='commanduser',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
